# Generated by Django 2.1.7 on 2019-03-27 14:13

import Application.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('building', models.CharField(max_length=200)),
                ('budget', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('salary', models.FloatField()),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_id', models.CharField(max_length=200)),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField(default=2016, validators=[Application.models.Section.yearValidator])),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Roll Number')),
                ('firstName', models.CharField(max_length=200, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=200, verbose_name='Last Name')),
                ('tot_cred', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Total Credits')),
                ('stud_img', models.ImageField(upload_to='media/', verbose_name='Image')),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.Department', verbose_name='Department Name')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='dept_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.Department'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='i_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.Instructor'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='s_id',
            field=models.ForeignKey(default='10', on_delete=django.db.models.deletion.CASCADE, to='Application.Student', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course_id', 'sec_id', 'semester', 'year')},
        ),
    ]
